[project]
name = "advanced_password_validator"
version = "0.1.0"
description = "A dynamic password validation system with preconfigured modes rule-based design"
readme = "README.md"
license = {file: "LICENSE"}
authors = [
    {name = "SimonTheDane", email = "STcena1@hotmail.com"}
]
dependencis = []

[project.urls]
homepage = ""
source = ""